### ISSUE TITLE
thank you map not working

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#15]
_eosrei created an issue 2014-12-11_
Halsey reports "thank you map not working; probably has to do with google maps key or Play services key?"

:x: A major issue

_Matthew Adler   2014-12-11_
What is a "thank you map?

_Halsey Burgund REPO OWNER 2014-12-12_
you know, the standard "thank you map" ;-) Sorry, this was clearly obtuse to anyone not familiar with RW apps.
The Thank You map is on the Thank You screen which is the screen that is displayed after a user submits a recording. Basically, it says, "Thanks for the submission; it'll be available in the mix soon". The bulk of this screen is supposed to be a map with a pin on it where the just-uploaded recording was made, but currently, the map is not showing up (for me at least). I can find an example from another map if this still doesn't make sense.

**Comment by 13rac1** [comment]
Confirmed. The map view is initialized, but no map content is shown.

Looks like this is related, but it's shows up rarely.

```
01-23 15:26:27.105    6442-6442/com.google.android.apps.maps D/StrictMode﹕ StrictMode policy violation; ~duration=629 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
            at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:106)
            at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
            at dalvik.system.DexPathList.findLibrary(DexPathList.java:384)
            at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
            at java.lang.Runtime.loadLibrary(Runtime.java:356)
            at java.lang.System.loadLibrary(System.java:526)
            at com.google.android.libraries.social.jni.crashreporter.NativeCrashHandler.a(PG:182)
            at com.google.android.libraries.social.jni.crashreporter.NativeCrashHandler.a(PG:81)
            at com.google.android.apps.gmm.base.app.b.<init>(PG:467)
            at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:84)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

Looks related: http://stackoverflow.com/questions/6700171/mapactivity-with-strictmode-does-not-work-help

**Comment by 13rac1** [comment]
Nah... That's not it at all! I fixed it. Pull request in a few.

**Comment by eosrei** [comment]
![screenshot_2015-01-23-19-09](https://cloud.githubusercontent.com/assets/195061/5885944/d2bdaa08-a333-11e4-8358-82f28b17bff1.jpg)
