### ISSUE TITLE
Attempting to record/speak without GPS location data available causes crash

### ISSUE THREAD

**Issue by 13rac1** [roundware/roundware-android#41]
Attempting to record/speak without GPS location data available results in crash. Occurs when user presses the `Upload` button after recording:

```
02-04 16:48:45.291    6596-6596/org.famsf.roundware E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.famsf.roundware, PID: 6596
    java.lang.RuntimeException: Unable to start service org.roundware.service.RWService@3c241405 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
            at android.app.ActivityThread.access$2100(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5255)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
            at android.content.ComponentName.<init>(ComponentName.java:78)
            at android.content.Intent.<init>(Intent.java:4082)
            at org.roundware.service.RWService.onStartCommand(RWService.java:755)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
            at android.app.ActivityThread.access$2100(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5255)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

Related to: #34 

Parent issue: #23

**Comment by 13rac1** [comment]
Parent issue: #23

**Comment by multidynamic** [comment]
@eosrei  This stack trace appears to be related to the generation of the pending intent notification.

Some sort of race condition with the class.forName method...
